name: build-wheels

on:
  push:
    tags:
    - 'v*'

jobs:
  build-python-wheels:
    name: Build Python Wheels for specific OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          TARGET: macos
        - os: ubuntu-latest
          TARGET: linux-amd64
        - os: windows-latest
          TARGET: win64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Prepare download folder
        run: mkdir download
        shell: pwsh
      - name: Install build dependencies
        run: pip install wheel
      - name: Build wheels for IDF master
        run: .\Build-Wheels.ps1  -Branch "master" -CompileWheels @("windows-curses")
      - name: Test wheels by installation
        run: .\Test-Wheels.ps1 -Branch "master"
      - name: Build wheels for IDF release/v4.2
        run: .\Build-Wheels.ps1  -Branch "release/v4.2" -CompileWheels @("windows-curses")
      - name: Test wheels by installation
        run: .\Test-Wheels.ps1 -Branch "release/v4.2"
      - name: Build wheels for IDF release/v4.1
        run: .\Build-Wheels.ps1  -Branch "release/v4.1" -CompileWheels @("windows-curses")
      - name: Test wheels by installation
        run: .\Test-Wheels.ps1 -Branch "release/v4.1"
      - name: Write version of package to file
        run: python -c  "print('3.9', file=open('download/version.txt', 'w'))"
      - name: Archive artifact
        run: Compress-Archive -Path "download\*" -DestinationPath "idf-python-wheels.zip"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./idf-python-wheels.zip
          asset_name: idf-python-wheels-3.9-${{ matrix.TARGET }}.zip
          asset_content_type: application/zip
